### ISSUE TITLE
Hardware volume buttons up & down both decrease volume when not in the main app

### ISSUE THREAD

**Issue by Landcross** [musicbeeremote/mbrc#228]
When I'm not in the MusicBee Remote app (but it is running in the background), both the volume up and down buttons decrease the volume. It can't be increased. Only within the actual app does the volume up button increase the volume.

I'm using plugin version 1.4.1.0 and the newest Android app.
My phone is an LG V30 with Android 9.

**Comment by kelsos** [comment]
I managed to verify the issue. It seems I had the wrong impression of how the volume adjustment worked.

**Comment by kelsos** [comment]
Fixed in v1.5.1. 

The volume now will change 1% with a single press of the button instead of 5% before, but keeping the hardware button pressed to each direction should keep increasing/decreasing the volume
