### ISSUE TITLE
That sht doesn't work.

### ISSUE THREAD

**Issue by Yeirry** [musicbeeremote/mbrc#249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Failed to connect and thats all. Blssht

### Environment

```markdown
- App Version:
- Android Version:
- Device: one plus
```

**Comment by kelsos** [comment]
Hey @Yeirry most of the times inability to connect can be tracked either to the user's network setup or to windows firewall actively blocking connections.

I understand your frustration but that does not excuse you not being civil.

That being said, the project is currently unmaintained as a have not the time or energy to continue development or provide further support.
